config/routes.rb
BaseballApp::Application.routes.draw do
  devise_for :users

  root to: "players#index"

  resources :players
  resources :batting_stats
  resources :batting_projections
  resources :leagues
  resources :notes
end

app/models/note.rb
class Note < ActiveRecord::Base
	attr_accessible :player_id, :user_id, :body

	validates :user_id, :player_id, :presence => true

	belongs_to :player 
	belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_filter :authenticate_user!

	def index
		@notes = Note.where(:user_id => current_user.id)
  end
  
  def show
  	@note = Note.find(params[:id])
  end
  
  def new
  	@note = Note.new(:player_id => params[:player_id])
  end
  
  def create
    @note = Note.new(params[:note])
    
    if @note.save
      redirect_to :root
    else
      render :new
    end
  end
  
  def edit
    @note = Note.find(params[:id])
  end
  
  def update
    @note = Note.find(params[:id])
    
    if @note.update_attributes(params[:note])
      redirect_to note_url(@note)
    else
      render :edit
    end
  end
  
  def destroy
    Note.find(params[:id]).destroy
    redirect_to :root
  end

end

app/views/notes/_form.html.erb
<div class="note-form">
	<%= form_for(@note) do |f| %>
		
		<%= f.text_area :body %>

		<%= f.hidden_field :player_id, :value => @note.player_id %>
		<%= f.hidden_field :user_id, :value => current_user.id %>

		<div id="note-button">
		<%= f.submit %>
		</div>
	<% end %>
</div>
	

app/views/notes/edit.html.erb
<%= render "form" %>

app/views/notes/index.html.erb
<div class="note-display">

<h2>All Notes</h2>

<ul>
	<% @notes.each do |note| %>
	<li><%= link_to note.player.name.split.map {|nm| nm.capitalize}.join(" "), note_path(note) %></li>
	<% end %>
</ul>

</div>

app/views/notes/new.html.erb
<%= render "form" %>

app/views/notes/show.html.erb
<div class="note-display">

	<div id="note-name">
	<%= @note.player.name.split.map{|nm| nm.capitalize}.join(" ") + ":" %>
	</div>

	<p>
		<%= @note.body %>
	</p>

</div>