config/routes.rb
BaseballApp::Application.routes.draw do
  devise_for :users

  root to: "players#index"

  resources :players
  resources :batting_stats
  resources :batting_projections
  resources :leagues
  resources :notes
end

app/models/player.rb
class Player < ActiveRecord::Base
	attr_accessible :fname, :lname, :age, :pos, :team_id, :batsman, :name

	validates :batsman, :inclusion => {:in => [true, false]}
	validates :pos, :presence => true
	validates :fname, :lname, :name, :presence => true
	validates :pos, :inclusion => {:in => (1..11).to_a}

	has_many :batting_projections
	#has_many :pitching_projections
	has_one :batting_stat
	#has_one :pitching_stat

	belongs_to :team
	delegate :circuit, :to => :team


	POSITION_NUMBERS = {
	"sp" => 1,
	"c" => 2,
	"1b" => 3,
	"2b" => 4,
	"3b" => 5,
	"ss" => 6,
	"lf" => 7,
	"cf" => 8,
	"rf" => 9,
	"dh" => 10,
	"rp" => 11
	}

	POSITION_TITLES = {
		1 => "Pitcher",
		2 => "Catchers",
		3 => "First Basemen",
		4 => "Second Basemen",
		5 => "Third Basemen",
		6 => "Shortstops",
		7 => "Left Fielders",
		8 => "Center Fielders",
		9 => "Right Fielders",
		10 => "Designated Hitters"
	}


	def Player.position_names 
		POSITION_NUMBERS.invert
	end

	def Player.position_name(n)
		Player.position_names[n]
	end

	def Player.position_title(n)
		POSITION_TITLES[n]
	end

	def Player.all_position_members(n)
		players = Player.where(:pos => n)
		players
	end

	def Player.search(search)
		if search
			find(:all, :conditions => ['fname LIKE ? OR lname LIKE ?', "%#{search}%", "%#{search}%"])
		else
			find(:all)
		end
	end

	def my_position_name
		Player.position_names[self.pos]
	end

	def team_name 
		self.team.name 
	end

	def circuit_name 
		self.circuit 
	end


end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def index
		if params[:search]
			@players = Player.search(params[:search])
		elsif params[:pos]
			@players = Player.where(:pos => params[:pos])
			@pos = params[:pos]
		else
			@players = Player.all
		end
	end

	def show
		@player = Player.find(params[:id])
	end
end

app/views/players/index.html.erb
<table id="player-table">


	<%= render partial: "positions/filter", :locals => {:controller => "players", :action => "index"} %> 

	<thead>
		<tr>
			<th>Name</th>
			<th>Position</th>
			<th>Team</th>
			<th>League</th>
		</tr>
	</thead>
	<tbody>
	<% @players.each do |player| %>
	<tr>
		<td>
		<%= link_to player.name.split(" ").map {|w| w.capitalize}.join(" "), player_url(player) %>
		</td>
		<td>
			<%= player.my_position_name.upcase %>
		</td> 
		<% if player.team_id %>
			<td>
				<%= player.team_name.upcase %> 
			</td> 
			<td>
				<%= player.circuit_name.upcase %>
			</td>
		<% else %>
			<td>
				<%= "FA" %>
			</td>
			<td>
				<%= "None" %>
			</td>
		<% end %>
	</tr>
	<% end %>
	
</tbody>
</table>

app/views/players/show.html.erb
<h2 id="player-name"><%= @player.fname.capitalize + " " + @player.lname.capitalize %></h2>

<section id="player-top" class="group">


	<div id="player-info">
		<ul>
			<li>Position: <%= @player.my_position_name.upcase %></li>
			<li>Team: <%= @player.team_name.capitalize %></li>
			<li>League: <%= @player.circuit_name.upcase %></li>
			<li>Age: <%= @player.age %></li>
			<li><%= link_to "Make A Note", new_note_path(:player_id => @player.id) %></li>
		</ul>
	</div>


</section>

<div class="player-numbers">
	<ul id="single-player-numbers">
			<% projection = @player.batting_projections.first %>
				Projections
				<li>
				<table class="stats-display">
					<%= display_header(BattingProjection.headers[1..-1]) %>
					<%= display_row(projection.row) %>
				</table>
			</li>
				Stats
			<li>
				<% if @player.batting_stat %>
					<table class="stats-display">
						<%= display_header(BattingStat.headers[1..-1]) %> 
						<%= display_row(@player.batting_stat.row) %>
					</table>
				<% else %>
					This player has no stats to display
				<% end %>
			</li>
		</ul>
</div>